services:
  yamcs:
    image: yamcs/example-simulation:5.11.7
    ports:
      - "8090:8090"
      - "50000:50000/udp"
      - "50001:50001/udp"
    volumes:
      - ./yamcs-data:/yamcs-data:ro
      - ./yamcs-data/mdb:/opt/yamcs/mdb:ro
    command: ["--etc-dir", "/yamcs-data/etc"]
