[pytest]
markers =
    uart_only: marks tests that sever the RF link (resets, TRANSMIT toggle) and should only be run when connected via UART
    sync_sequence_number: marks the test that synchronizes the sequence number between GDS and flight software; should be run before any other tests to avoid sequence number mismatches
    format_filesystem: marks the test that formats the filesystem; should be run before any other tests to ensure a clean state
filterwarnings =
    ignore::DeprecationWarning:yamcs\..*
    ignore::DeprecationWarning:google\.protobuf\..*
