name: Flash Firmware
description: Reboot integration hardware, flash MCUBoot and flight software via OpenOCD, reboot again.

runs:
  using: composite
  steps:
    - name: Reboot Integration Cube (before flash)
      shell: bash
      run: |
        ~/korad_control/.venv/bin/python ~/korad_control/korad_control.py -d /dev/ttyPWR --output 0
        sleep 3
        ~/korad_control/.venv/bin/python ~/korad_control/korad_control.py -d /dev/ttyPWR --output 1
        sleep 3

    - name: Install MCUBoot
      shell: bash
      run: |
        ~/openocd/src/openocd -s ~/openocd/tcl -f ~/openocd/tcl/interface/cmsis-dap.cfg -f ~/openocd/tcl/target/rp2350.cfg -c "adapter speed 5000" -c "program mcuboot.elf verify reset exit"
        sleep 3

    - name: Install Flight Software
      shell: bash
      run: |
        ~/openocd/src/openocd -s ~/openocd/tcl -f ~/openocd/tcl/interface/cmsis-dap.cfg -f ~/openocd/tcl/target/rp2350.cfg -c "adapter speed 5000" -c "program bootable.signed.hex verify reset exit"
        sleep 3

    - name: Reboot Integration Cube (after flash)
      shell: bash
      run: |
        ~/korad_control/.venv/bin/python ~/korad_control/korad_control.py -d /dev/ttyPWR --output 0
        sleep 3
        ~/korad_control/.venv/bin/python ~/korad_control/korad_control.py -d /dev/ttyPWR --output 1
        sleep 3
